server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        show_sql: true

  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB

app:
  jwt:
    time-in-minutes: 20
    secret: ${APP_JWT_SECRET}