server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://dpg-d15sdg0dl3ps7384m040-a.oregon-postgres.render.com:5432/registryapp_meih
    username: adminibet
    password: YkpI5mf8OGZcN7C5NGEbRqUuzeIGuA8O
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        show_sql: true

  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB

app:
  jwt:
    time-in-minutes: 20
    secret: r3g157ry_499l1c4t10n_574nd4rd_cl13n7_53cr37