server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://db.kgohwpartnjsnlnuqtrk.supabase.co:5432/postgres?sslmode=require
    username: postgres
    password: RegistryAppPsw
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        show_sql: true

  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB

app:
  jwt:
    time-in-minutes: 20
    secret: r3g157ry_499l1c4t10n_574nd4rd_cl13n7_53cr37